accounts/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutpage, name='logout'),
    path('signup/', views.registerpage, name='signup'),
]

school/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('management.urls')),
    path('', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

accounts/models.py
from django.db import models

# Create your models here.

management/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import *
from django.contrib.auth.forms import UserCreationForm


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()
    
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']
        
        
class ProfileUdateForm(forms.ModelForm):
    
    class Meta:
        model = Profile
        fields = '__all__'
        exclude = ['user']
        
    def __init__(self, *args, **kwargs):
        super(ProfileUdateForm, self).__init__(*args, **kwargs)
        self.fields['State'].empty_label = '--Select State--'
        
    # def __init__(self, *args, **kwargs):
    #     super(ProfileUdateForm, self).__init__(*args, **kwargs)
    #     self.fields['position'].empty_label = 'select'
        
        
        
class Userprofileform(forms.ModelForm):
    
    class Meta:
        model = Profile
        fields = ['profile_pic']
        

class CreateUserForm(UserCreationForm):
    username = forms.CharField(label='Your Username')
    email = forms.EmailField(required=True, label='Your Email')
    last_name = forms.CharField(max_length=30, label='Your Surname')
    first_name = forms.CharField(max_length=30, label='Your Full name')
    password1 = forms.CharField(max_length=30, label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(max_length=30, label='Repeat your password', widget=forms.PasswordInput)
    
    
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']
    
    def save(self, commit=True):
        user = super().save(commit=False)
        
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        
        if commit:
            user.save()
        return user
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name in self.fields:
            field = self.fields.get(field_name)
            self.fields[field_name].widget.attrs.update({
                "placeholder": field.label,
                'class': "input-control"
            })
        
class ApplicationForm(forms.ModelForm):
    class Meta:
        model = LeaveDetail
        fields = '__all__'
        exclude = ['author']
        labels = {   
            'Reason': 'Reason/Comments',
        }
        

    def __init__(self, *args, **kwargs):
        super(ApplicationForm, self).__init__(*args, **kwargs)
        self.fields['leave_type'].empty_label = 'Choice Leave Type'
        
        
        
        
        
        
        
        
# from bootstrap_datepicker_plus import DatePickerInput
# from django import forms

# # Custom Form usage
# class ToDoForm(forms.Form):
#     todo = forms.CharField(
#         widget=forms.TextInput(attrs={"class": "form-control"})
#     )
#     date = forms.DateField(
#         widget=DatePickerInput(format='%m/%d/%Y')
#     )
    
    
# # Model Form usage    
# class EventForm(forms.ModelForm):
#     class Meta:
#         model = Event
#         fields = ['name', 'start_date', 'end_date']
#         widgets = {
#             'start_date': DatePickerInput(), # default date-format %m/%d/%Y will be used
#             'end_date': DatePickerInput(format='%Y-%m-%d'), # specify date-frmat
#         }
   
# # Types of DatePickers        
# class EventForm(forms.ModelForm):
#     class Meta:
#         model = Event
#         fields = ['start_date', 'start_time', 'start_datetime', 'start_month', 'start_year']
#         widgets = {
#             'start_date': DatePickerInput(),
#             'start_time': TimePickerInput(),
#             'start_datetime': DateTimePickerInput(),
#             'start_month': MonthPickerInput(),
#             'start_year': YearPickerInput(),
#         }
        
# # Implement date-range-picker
# class EventForm(forms.ModelForm):
#     class Meta:
#         model = Event
#         fields = ['name', 'start_date', 'end_date', 'start_time', 'end_time']
#         widgets = {
#             'start_date':DatePickerInput().start_of('event days'),
#             'end_date':DatePickerInput().end_of('event days'),
#             'start_time':TimePickerInput().start_of('party time'),
#             'end_time':TimePickerInput().end_of('party time'),
#         }

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from management.decorators import unauthenticated_user, allowed_users, admin_only
from management.forms import Userprofileform, CreateUserForm

# Create your views here.
def loginPage(request):
    # login Validation
    if request.user.is_authenticated:
        return redirect('home')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')
            
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('home')
            else:
                messages.info(request, 'Username Or Password is Incorrect')

    
    return render(request, 'accounts/login.html')


def logoutpage(request):
    logout(request)
    return redirect('homepage')


@allowed_users(allowed_roles=['Manager'])
def registerpage(request):
    if request.user.is_authenticated:
        return redirect('home')
    else:    
        if request.method == 'POST':
            c_form = CreateUserForm(request.POST)
            p_form = Userprofileform(request.POST, request.FILES)
            
            if c_form.is_valid() and p_form.is_valid():
                user = c_form.save()
                
                profile = p_form.save(commit=False)
                profile.user = user
                
                p_form.save()
                
                username = c_form.cleaned_data.get('username')
                messages.success(request, f'Account was created for {username}')
                return redirect('home')
        else:
            c_form = CreateUserForm()
            p_form = Userprofileform()

        context={
            'c_form': c_form,
            'p_form': p_form,
        }
        return render(request, 'accounts/signup.html', context)

accounts/templates/accounts/login.html
{% extends 'accounts/main.html' %}
{% load static %}

{% block account %}

       <section class="sign-in">
            <div class="container">
                <div class="signin-content">
                    <div class="signin-image" style="margin-top: 8%;">
                        <figure><img src="{% static 'images/signin-image.jpg' %}" alt="sing up image"></figure>
                    </div>

                    <div class="signin-form" style="margin-top: 8%;">
                        <h2 class="form-title">Login</h2>

                        <form method="POST" class="register-form" id="login-form">
						{% csrf_token %}
                            <div class="form-group">
                                <label for="your_name"><i class="zmdi zmdi-account material-icons-name"></i></label>
                                <input type="text" name="username" id="your_name" placeholder="Your Username" required-title="Enter Your Username"/>
                            </div>
                            <div class="form-group">
                                <label for="your_pass"><i class="zmdi zmdi-lock"></i></label>
                                <input type="password" name="password" id="your_pass" placeholder="Password"/>
                            </div>
                                {% if messages %}
         			     {% for message in messages %}
                  <span style="color:red;">{{ message }}</span>
           		   {% endfor %}
           			{% endif %}
                            <div class="form-group form-button">
                                <input type="submit" name="signin" id="signin" class="form-submit" value="Log in"/>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </section>

 
{% endblock  %}

accounts/templates/accounts/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Accounts</title>

    <!-- Font Icon -->
    <link rel="stylesheet" href="{% static 'fonts/material-icon/css/material-design-iconic-font.min.css' %}">

    <!-- Main css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

<div class="main">
{% block account %}

{% endblock  %}
</div>

    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

accounts/templates/accounts/signup.html
{% extends 'accounts/main.html' %}
{% load static %}

{% block account %}
        <section class="signup">
            <div class="container">
                <div class="signup-content">
                    <div class="signup-form">
                        <h2 class="form-title">Sign up</h2>

                        <form method="POST" class="register-form" id="register-form" enctype="multipart/form-data">
                            {% csrf_token %}
                            
                            <div class="form-group">
                                <label for="id_username"><i class="zmdi zmdi-account material-icons-name"></i></label>
                                {{ c_form.username }}
                            </div>
                            <div class="form-group">
                                <label for="id_last_name"><i class="zmdi zmdi-account material-icons-name"></i></label>
                                {{ c_form.last_name }}
                            </div>
                            <div class="form-group">
                                <label for="id_first_name"><i class="zmdi zmdi-account material-icons-name"></i></label>
                                {{ c_form.first_name }}
                            </div>
                            <div class="form-group">
                                <label for="id_email"><i class="zmdi zmdi-email"></i></label>
                                {{ c_form.email }}
                            </div>
                            <div class="form-group">
                                <label for="id_password1"><i class="zmdi zmdi-lock"></i></label>
                                {{ c_form.password1 }}
                            </div>
                            <div class="form-group">
                                <label for="id_password2"><i class="zmdi zmdi-lock-outline"></i></label>
                                {{ c_form.password2 }}
                            </div>
                            <div>
                                {{ p_form.profile_pic }}
                            </div>
                            
                            <div class="form-group form-button">
                                <input type="submit" name="signup" id="signup" class="form-submit" value="Register"/>
                            </div>

                            {{ c_form.errors }}
                            {{ p_form.errors }}
                        </form>

                    </div>
                    <div class="signup-image">
                        <figure><img src="{% static 'images/signup-image.jpg' %}" alt="sign up image"></figure>
                    </div>
                </div>
            </div>
        </section>

{% endblock %}